export const destinations = [
  {
    id: 1,
    name: "北海道・札幌",
    region: "北海道",
    specialty: "ジンギスカン、雪まつり",
    description: "雄大な自然と美味しいグルメが楽しめる北の大地",
    emoji: "🦐",
  },
  {
    id: 2,
    name: "北海道・函館",
    region: "北海道",
    specialty: "海鮮丼、夜景",
    description: "美しい夜景と新鮮な海の幸が楽しめる港町",
    emoji: "🌃",
  },
  {
    id: 3,
    name: "青森・弘前",
    region: "東北",
    specialty: "りんご、ねぶた祭り",
    description: "美しい桜で有名な弘前城がある街",
    emoji: "🍎",
  },
  {
    id: 4,
    name: "岩手・平泉",
    region: "東北",
    specialty: "わんこそば、中尊寺",
    description: "平安時代の文化が息づく世界遺産の町",
    emoji: "⛩️",
  },
  {
    id: 5,
    name: "宮城・仙台",
    region: "東北",
    specialty: "牛タン、ずんだ餅",
    description: "杜の都として知られる東北最大の都市",
    emoji: "🥩",
  },
  {
    id: 6,
    name: "山形・山寺",
    region: "東北",
    specialty: "温泉、さくらんぼ",
    description: "立石寺で有名な自然に囲まれた霊場",
    emoji: "🍒",
  },
  {
    id: 7,
    name: "福島・会津若松",
    region: "東北",
    specialty: "赤べこ、ソースカツ丼",
    description: "戊辰戦争の舞台となった歴史ある城下町",
    emoji: "🏯",
  },
  {
    id: 8,
    name: "茨城・袋田の滝",
    region: "関東",
    specialty: "納豆、あんこう鍋",
    description: "日本三大名瀑の一つ、四季折々の美しさ",
    emoji: "💧",
  },
  {
    id: 9,
    name: "栃木・日光",
    region: "関東",
    specialty: "湯波、いろは坂",
    description: "東照宮と華厳の滝で有名な世界遺産の地",
    emoji: "🦌",
  },
  {
    id: 10,
    name: "群馬・草津温泉",
    region: "関東",
    specialty: "温泉まんじゅう、湯もみ",
    description: "日本三名泉の一つ、湯畑で有名な温泉地",
    emoji: "♨️",
  },
  {
    id: 11,
    name: "埼玉・川越",
    region: "関東",
    specialty: "芋菓子、時の鐘",
    description: "小江戸として親しまれる蔵造りの街並み",
    emoji: "🏮",
  },
  {
    id: 12,
    name: "千葉・成田山",
    region: "関東",
    specialty: "うなぎ、落花生",
    description: "成田山新勝寺で有名な参拝地",
    emoji: "🥜",
  },
  {
    id: 13,
    name: "東京・浅草",
    region: "関東",
    specialty: "雷おこし、もんじゃ焼き",
    description: "江戸情緒あふれる下町文化の中心地",
    emoji: "🗼",
  },
  {
    id: 14,
    name: "神奈川・箱根",
    region: "関東",
    specialty: "温泉、寄木細工",
    description: "富士山を望む温泉リゾート地",
    emoji: "🗻",
  },
  {
    id: 15,
    name: "新潟・越後湯沢",
    region: "中部",
    specialty: "コシヒカリ、スキー",
    description: "川端康成『雪国』の舞台となった温泉地",
    emoji: "⛷️",
  },
  {
    id: 16,
    name: "富山・立山",
    region: "中部",
    specialty: "ますずし、雪の大谷",
    description: "3000m級の山々と雪の大谷で有名",
    emoji: "🏔️",
  },
  {
    id: 17,
    name: "石川・金沢",
    region: "中部",
    specialty: "金箔、加賀料理",
    description: "兼六園で有名な加賀百万石の城下町",
    emoji: "⭐",
  },
  {
    id: 18,
    name: "福井・恐竜博物館",
    region: "中部",
    specialty: "越前がに、恐竜化石",
    description: "世界有数の恐竜化石の産地",
    emoji: "🦕",
  },
  {
    id: 19,
    name: "山梨・河口湖",
    region: "中部",
    specialty: "ほうとう、富士山",
    description: "富士五湖の一つ、富士山の絶景スポット",
    emoji: "🌸",
  },
  {
    id: 20,
    name: "長野・軽井沢",
    region: "中部",
    specialty: "そば、高原野菜",
    description: "避暑地として親しまれる高原リゾート",
    emoji: "🌲",
  },
  {
    id: 21,
    name: "岐阜・高山",
    region: "中部",
    specialty: "飛騨牛、さるぼぼ",
    description: "飛騨の小京都と呼ばれる古い町並み",
    emoji: "🏔️",
  },
  {
    id: 22,
    name: "静岡・熱海",
    region: "中部",
    specialty: "温泉、海の幸",
    description: "伊豆半島の玄関口にある温泉街",
    emoji: "🌊",
  },
  {
    id: 23,
    name: "愛知・名古屋",
    region: "中部",
    specialty: "味噌カツ、ひつまぶし",
    description: "独特の食文化で知られる中部地方の中心都市",
    emoji: "🍱",
  },
  {
    id: 24,
    name: "三重・伊勢神宮",
    region: "関西",
    specialty: "伊勢うどん、赤福",
    description: "日本人の心のふるさと、お伊勢参り",
    emoji: "⛩️",
  },
  {
    id: 25,
    name: "滋賀・彦根城",
    region: "関西",
    specialty: "近江牛、ひこにゃん",
    description: "国宝の天守閣とひこにゃんで有名",
    emoji: "🏯",
  },
  {
    id: 26,
    name: "京都・祇園",
    region: "関西",
    specialty: "抹茶、京料理",
    description: "古き良き日本の文化が息づく古都",
    emoji: "🏛️",
  },
  {
    id: 27,
    name: "大阪・道頓堀",
    region: "関西",
    specialty: "たこ焼き、お好み焼き",
    description: "食い倒れの街として有名なグルメの聖地",
    emoji: "🐙",
  },
  {
    id: 28,
    name: "兵庫・神戸",
    region: "関西",
    specialty: "神戸牛、中華街",
    description: "異国情緒あふれる港町",
    emoji: "🥩",
  },
  {
    id: 29,
    name: "奈良・東大寺",
    region: "関西",
    specialty: "柿の葉寿司、鹿せんべい",
    description: "大仏様と鹿で親しまれる古都",
    emoji: "🦌",
  },
  {
    id: 30,
    name: "和歌山・熊野古道",
    region: "関西",
    specialty: "梅干し、温泉",
    description: "世界遺産の熊野古道と熊野三山",
    emoji: "🥾",
  },
  {
    id: 31,
    name: "鳥取・砂丘",
    region: "中国",
    specialty: "二十世紀梨、砂丘らっきょう",
    description: "日本最大級の砂丘が広がる絶景地",
    emoji: "🏜️",
  },
  {
    id: 32,
    name: "島根・出雲大社",
    region: "中国",
    specialty: "出雲そば、しじみ",
    description: "縁結びの神様で有名な古社",
    emoji: "💕",
  },
  {
    id: 33,
    name: "岡山・倉敷",
    region: "中国",
    specialty: "白桃、倉敷デニム",
    description: "美観地区の白壁が美しい歴史の街",
    emoji: "🏘️",
  },
  {
    id: 34,
    name: "広島・宮島",
    region: "中国",
    specialty: "牡蠣、もみじまんじゅう",
    description: "厳島神社の鳥居で有名な風光明媚な島",
    emoji: "⛩️",
  },
  {
    id: 35,
    name: "山口・萩",
    region: "中国",
    specialty: "河豚、夏みかん",
    description: "幕末の志士を育んだ歴史ある城下町",
    emoji: "🌊",
  },
  {
    id: 36,
    name: "徳島・祖谷渓",
    region: "四国",
    specialty: "阿波踊り、すだち",
    description: "かずら橋と深い谷で知られる秘境",
    emoji: "🌉",
  },
  {
    id: 37,
    name: "香川・高松",
    region: "四国",
    specialty: "讃岐うどん、オリーブ",
    description: "うどん県として親しまれる四国の玄関口",
    emoji: "🍜",
  },
  {
    id: 38,
    name: "愛媛・道後温泉",
    region: "四国",
    specialty: "温泉、みかん",
    description: "日本最古の温泉として知られる歴史ある温泉地",
    emoji: "🍊",
  },
  {
    id: 39,
    name: "高知・桂浜",
    region: "四国",
    specialty: "カツオのたたき、坂本龍馬",
    description: "坂本龍馬像と美しい砂浜で有名",
    emoji: "🐟",
  },
  {
    id: 40,
    name: "福岡・博多",
    region: "九州",
    specialty: "ラーメン、明太子",
    description: "九州最大の都市でグルメの宝庫",
    emoji: "🍜",
  },
  {
    id: 41,
    name: "佐賀・有田",
    region: "九州",
    specialty: "有田焼、イカ",
    description: "400年の歴史を持つ陶磁器の里",
    emoji: "🏺",
  },
  {
    id: 42,
    name: "長崎・ハウステンボス",
    region: "九州",
    specialty: "カステラ、ちゃんぽん",
    description: "異国情緒あふれるテーマパークがある街",
    emoji: "🏰",
  },
  {
    id: 43,
    name: "熊本・阿蘇",
    region: "九州",
    specialty: "馬刺し、阿蘇の自然",
    description: "雄大なカルデラと温泉で有名",
    emoji: "🌋",
  },
  {
    id: 44,
    name: "大分・別府温泉",
    region: "九州",
    specialty: "地獄蒸し、温泉",
    description: "日本一の温泉湧出量を誇る温泉王国",
    emoji: "♨️",
  },
  {
    id: 45,
    name: "宮崎・高千穂",
    region: "九州",
    specialty: "チキン南蛮、神話",
    description: "天照大神の神話で有名な神秘の峡谷",
    emoji: "🌟",
  },
  {
    id: 46,
    name: "鹿児島・指宿",
    region: "九州",
    specialty: "砂風呂、黒豚",
    description: "砂蒸し温泉で有名な薩摩半島の温泉地",
    emoji: "🐷",
  },
  {
    id: 47,
    name: "沖縄・那覇",
    region: "沖縄",
    specialty: "ソーキそば、ちんすこう",
    description: "青い海と独特の文化が魅力の南の島",
    emoji: "🏝️",
  },
  {
    id: 48,
    name: "沖縄・石垣島",
    region: "沖縄",
    specialty: "石垣牛、マンゴー",
    description: "エメラルドグリーンの海とサンゴ礁の楽園",
    emoji: "🐠",
  },
];
