export const destinations = [
  {
    id: 1,
    name: "北海道・札幌",
    region: "北海道",
    specialty: "ジンギスカン、雪まつり",
    description: "雄大な自然と美味しいグルメが楽しめる北の大地",
    emoji: "🦐",
  },
  {
    id: 2,
    name: "青森・弘前",
    region: "東北",
    specialty: "りんご、ねぶた祭り",
    description: "美しい桜で有名な弘前城がある街",
    emoji: "🍎",
  },
  {
    id: 3,
    name: "宮城・仙台",
    region: "東北",
    specialty: "牛タン、ずんだ餅",
    description: "杜の都として知られる東北最大の都市",
    emoji: "🥩",
  },
  {
    id: 4,
    name: "東京・浅草",
    region: "関東",
    specialty: "雷おこし、もんじゃ焼き",
    description: "江戸情緒あふれる下町文化の中心地",
    emoji: "🗼",
  },
  {
    id: 5,
    name: "神奈川・箱根",
    region: "関東",
    specialty: "温泉、寄木細工",
    description: "富士山を望む温泉リゾート地",
    emoji: "🗻",
  },
  {
    id: 6,
    name: "静岡・熱海",
    region: "中部",
    specialty: "温泉、海の幸",
    description: "伊豆半島の玄関口にある温泉街",
    emoji: "♨️",
  },
  {
    id: 7,
    name: "愛知・名古屋",
    region: "中部",
    specialty: "味噌カツ、ひつまぶし",
    description: "独特の食文化で知られる中部地方の中心都市",
    emoji: "🍱",
  },
  {
    id: 8,
    name: "京都・祇園",
    region: "関西",
    specialty: "抹茶、京料理",
    description: "古き良き日本の文化が息づく古都",
    emoji: "🏛️",
  },
  {
    id: 9,
    name: "大阪・道頓堀",
    region: "関西",
    specialty: "たこ焼き、お好み焼き",
    description: "食い倒れの街として有名なグルメの聖地",
    emoji: "🐙",
  },
  {
    id: 10,
    name: "兵庫・神戸",
    region: "関西",
    specialty: "神戸牛、中華街",
    description: "異国情緒あふれる港町",
    emoji: "🥩",
  },
  {
    id: 11,
    name: "広島・宮島",
    region: "中国",
    specialty: "牡蠣、もみじまんじゅう",
    description: "厳島神社の鳥居で有名な風光明媚な島",
    emoji: "⛩️",
  },
  {
    id: 12,
    name: "香川・高松",
    region: "四国",
    specialty: "讃岐うどん、オリーブ",
    description: "うどん県として親しまれる四国の玄関口",
    emoji: "🍜",
  },
  {
    id: 13,
    name: "愛媛・道後温泉",
    region: "四国",
    specialty: "温泉、みかん",
    description: "日本最古の温泉として知られる歴史ある温泉地",
    emoji: "🍊",
  },
  {
    id: 14,
    name: "福岡・博多",
    region: "九州",
    specialty: "ラーメン、明太子",
    description: "九州最大の都市でグルメの宝庫",
    emoji: "🍜",
  },
  {
    id: 15,
    name: "長崎・ハウステンボス",
    region: "九州",
    specialty: "カステラ、ちゃんぽん",
    description: "異国情緒あふれるテーマパークがある街",
    emoji: "🏰",
  },
  {
    id: 16,
    name: "熊本・阿蘇",
    region: "九州",
    specialty: "馬刺し、阿蘇の自然",
    description: "雄大なカルデラと温泉で有名",
    emoji: "🌋",
  },
  {
    id: 17,
    name: "鹿児島・指宿",
    region: "九州",
    specialty: "砂風呂、黒豚",
    description: "砂蒸し温泉で有名な薩摩半島の温泉地",
    emoji: "🐷",
  },
  {
    id: 18,
    name: "沖縄・那覇",
    region: "沖縄",
    specialty: "ソーキそば、ちんすこう",
    description: "青い海と独特の文化が魅力の南の島",
    emoji: "🏝️",
  },
  {
    id: 19,
    name: "石川・金沢",
    region: "中部",
    specialty: "金箔、加賀料理",
    description: "兼六園で有名な加賀百万石の城下町",
    emoji: "⭐",
  },
  {
    id: 20,
    name: "岐阜・高山",
    region: "中部",
    specialty: "飛騨牛、さるぼぼ",
    description: "飛騨の小京都と呼ばれる古い町並み",
    emoji: "🏔️",
  },
];
